# Nom del lloc
site_name: Programació

# Carpeta amb el documents font
docs_dir: 'md'

# Carpeta on es generarà el lloc web (mkdocs build)
site_dir: 'docs'

# Adreça on s'executa el server local (mkdocs serve)
dev_addr: localhost:4000

# Navegació dels documents
# nav:
#   - Títol: Document.md
nav:
  - Inicio: index.md
  - UD 0 Conocimientos previos:
      - 0.1 Introducción: ud00/ud0001.md
      - 0.2 Markdown: ud00/ud0002.md
      - 0.3 Git: ud00/ud0003.md
      - 0.3 Github: ud00/ud0004.md
      - 0.5 VS Code: ud00/ud0005.md
      - Actividades: ud00/ud00ac.md
      - Fuentes de información: ud00/ud00re.md
  - UD 1 Elemenos de un programa informático:
      - 1.1 Piensa como un programador: ud01/ud0101.md
      - 1.2 Problemas, algoritmos y programas: ud01/ud0102.md
      - 1.3 Java: ud01/ud0103.md
      - 1.4 Variables, identificadores, convenciones: ud01/ud0104.md
      - 1.5 Tipos de datos: ud01/ud0105.md
      - 1.6 Tipos referenciados: ud01/ud0106.md
      - 1.7 Tipos enumerados: ud01/ud0107.md
      - 1.8 Constantes y literales: ud01/ud0108.md
      - 1.9 Operadores y expresiones: ud01/ud0109.md
      - 1.10 Conversiones de tipo: ud01/ud0110.md
      - 1.11 Comentarios: ud01/ud0111.md
      - 1.12 Herramientas útiles para empezar: ud01/ud0112.md
      - 1.13 Instalar Java en Linux: ud01/ud0113.md
      - 1.14 Instalar Java en Windows: ud01/ud0114.md
      - Ejemplos: ud01/ud0115.md
      - Actividades: ud01/ud01ac.md
      - Píldoras informáticas: ud01/ud01pi.md
      - Fuentes de información: ud01/ud01re.md
  - UD 2 Utilización de objetos y clases:
      - 2.1 Introducción a la POO: ud02/ud0201.md
      - 2.2 Características de la POO: ud02/ud0202.md
      - 2.3 Objetos y Clases: ud02/ud0203.md
      - 2.4 Utilización de objetos: ud02/ud0204.md
      - 2.5 Utilización de métodos: ud02/ud0205.md
      - 2.6 Librerías de objetos (paquetes): ud02/ud0206.md
      - 2.7 Cadenas de caracteres. La clase String: ud02/ud0207.md
      - Ejemplos: ud02/ud0208.md
      - Actividades: ud02/ud02ac.md
      - Píldoras informáticas: ud02/ud02pi.md
      - Fuentes de información: ud02/ud02re.md
  - UD 3 Estructuras de control y excepciones:
      - 3.1 Introducción: ud03/ud0301.md
      - 3.2 Sentencias y bloques: ud03/ud0302.md
      - 3.3 Sentencias de selección: ud03/ud0303.md
      - 3.4 Estructuras de repetición: ud03/ud0304.md
      - 3.5 Estructuras de salto: ud03/ud0305.md
      - 3.6 Excepciones: ud03/ud0306.md
      - Actividades: ud03/ud03ac.md
      - Píldoras informáticas: ud03/ud03pi.md
      - Fuentes de información: ud03/ud03re.md
  - UD 4 Estructuras de datos Arrays y matrices. Recursividad:
      - 4.1 Introducción: ud04/ud0401.md
      - 4.2 Arrays: ud04/ud0402.md
      - 4.3 Problemas de recorrido, búsqueda y ordenación: ud04/ud0403.md
      - 4.4 Arrays bidimensionales: ud04/ud0404.md
      - 4.5 Arrays multidimensionales: ud04/ud0405.md
      - 4.6 Recursividad: ud04/ud0406.md
      - 4.7 Anexos: ud04/ud0407.md
      - Actividades: ud04/ud04ac.md
      - Píldoras informáticas: ud04/ud04pi.md
      - Fuentes de información: ud04/ud04re.md
  - UD 5 Desarrollo de clases:
      - 5.1 Introducción: ud05/ud0501.md
      - 5.2 Estructura y miembros de una clase: ud05/ud0502.md
      - 5.3 Atributos: ud05/ud0503.md
      - 5.4 Métodos: ud05/ud0504.md
      - 5.5 Encapsulación, control de acceso y visibilidad: ud05/ud0505.md
      - 5.6 Utilización de métodos y atributos de una clase: ud05/ud0506.md
      - 5.7 Constructores: ud05/ud0507.md
      - 5.8 Introducción a la herencia: ud05/ud0508.md
      - 5.9 Empaquetado de clases: ud05/ud0509.md
      - 5.10 Anexos: ud05/ud0510.md
      - Actividades: ud05/ud05ac.md
      - Píldoras informáticas: ud05/ud05pi.md
      - Fuentes de información: ud05/ud05re.md
  - UD 6 Lectura y escritura de información:
      - 6.1 Streams (flujos): ud06/ud0601.md
      - 6.2 Ficheros: ud06/ud0602.md
      - 6.3 Serialización: ud06/ud0603.md
      - 6.4 Sockets: ud06/ud0604.md
      - 6.5 Manejo de ficheros y carpetas: ud06/ud0605.md
      - 6.6 Comparativa CRUD: ud06/ud0606.md
      - Actividades: ud06/ud06ac.md
      - Píldoras informáticas: ud06/ud06pi.md
      - Fuentes de información: ud06/ud06re.md
  - UD 7 Colecciones:
      - 7.1 Introducción: ud07/ud0701.md
      - 7.2 Colecciones: ud07/ud0702.md
      - 7.3 Iteradores: ud07/ud0703.md
      - 7.4 Comparadores: ud07/ud0704.md
      - 7.5 Extras: ud07/ud0705.md
      - 7.6 Programación funcional: ud07/ud0706.md
      - Actividades: ud07/ud07ac.md
      - Píldoras informáticas: ud07/ud07pi.md
      - Fuentes de información: ud07/ud07re.md
  - UD 8 Composición, Herencia y Polimorfismo:
      - 8.1 Relaciones entre clases: ud08/ud0801.md
      - 8.2 Composición: ud08/ud0802.md
      - 8.3 Herencia: ud08/ud0803.md
      - 8.4 Clases abstractas: ud08/ud0804.md
      - 8.5 Interfaces: ud08/ud0805.md
      - 8.6 Polimorfismo: ud08/ud0806.md
      - Actividades: ud08/ud08ac.md
      - Píldoras informáticas: ud08/ud08pi.md
      - Fuentes de información: ud08/ud08re.md
  - UD 9 Acceso a bases de datos:
      - 9.1 Introducción: ud09/ud0901.md
      - 9.2 JDBC: ud09/ud0902.md
      - 9.3 Acceso a BBDD: ud09/ud0903.md
      - 9.4 Navegabilidad y concurrencia: ud09/ud0904.md
      - 9.5 Consultas (Query): ud09/ud0905.md
      - 9.6 Modificación (update): ud09/ud0906.md
      - 9.7 Inserción (insert): ud09/ud0907.md
      - 9.8 Borrado (delete): ud09/ud0908.md
      - 9.9 Sentencias predefinidas: ud09/ud0909.md
      - 9.10 Trabajar con Sqlite: ud09/ud0910.md
      - 9.11 Repository pattern: ud09/ud0911.md
      - Actividades: ud09/ud09ac.md
      - Píldoras informáticas: ud09/ud09pi.md
      - Fuentes de información: ud09/ud09re.md
  - UD 10 Interfaz gráfica: default.md

# Extensions
markdown_extensions:
  - admonition
  - attr_list         # permet afegir atributs a les etiquetes html
  # pymdownx és una col·leccio per escritura tècnica. S'instal·la per defecte
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true

# Tema a triar
theme:
  name: material  # selecció del tema
  logo: logo.png
  palette:
   # Boto que canvia a mode oscur
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Canvia a mode oscur
    # Botó que canvia a mode clar
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Canvia a mode normal
  features:
    # utilitats de copia de codi
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer       # footer de la pagina, amb navegació
    - navigation.top    # boto flotant de tornar a dalt

# Altres afegits
plugins:
  - search      # plugin del quadre cerca
  #- mkdocs-awesome-pages-plugin  # per a caixe awesomebox
  #- pdf-export  # plugin per exportar a pdf
  #- mkdocs-pdf-export-plugin

extra:
  favicon: favicon.ico

extra_css:
  - custom.css
